# Generated by Django 2.1.2 on 2019-03-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=40)),
                ('cost', models.FloatField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
